name: Documentation

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper versioning

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz cmake build-essential

    - name: Configure CMake (to set up Doxygen dependencies)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Generate documentation
      run: |
        cd build
        make voltray-docs

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/docs

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
